# Generated by Django 2.2.12 on 2020-04-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_testmodel_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='desc',
        ),
    ]
