# Generated by Django 2.2.12 on 2020-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_testmodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='file',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
    ]
