# Generated by Django 3.0 on 2020-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=200)),
                ('Subject_Code', models.CharField(max_length=200)),
                ('Max_Marks', models.IntegerField()),
                ('Course', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Semester', models.IntegerField()),
            ],
        ),
    ]
