# Generated by Django 3.0.6 on 2020-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('subcode', models.CharField(max_length=60)),
                ('marks_obtain', models.IntegerField()),
                ('upload', models.FileField(upload_to='marksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('subcode', models.CharField(max_length=60)),
                ('marks_obtain', models.IntegerField()),
                ('upload', models.FileField(upload_to='marksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('subcode', models.CharField(max_length=60)),
                ('marks_obtain', models.IntegerField()),
                ('upload', models.FileField(upload_to='marksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('subcode', models.CharField(max_length=60)),
                ('marks_obtain', models.IntegerField()),
                ('upload', models.FileField(upload_to='marksheet')),
            ],
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.FileField(upload_to='marksheet')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studname', models.CharField(max_length=100)),
                ('studroll', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=60)),
                ('sem', models.IntegerField()),
                ('mobile', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=100)),
                ('gen', models.CharField(max_length=100)),
                ('add', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('reg', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=200)),
                ('Subject_Code', models.CharField(max_length=200)),
                ('Max_Marks', models.IntegerField()),
                ('Course', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=100)),
                ('Semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('upload', models.FileField(upload_to='marksheet')),
            ],
        ),
    ]
