# Generated by Django 3.0 on 2020-04-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('marks_obtain', models.IntegerField()),
                ('sub_code', models.CharField(max_length=200)),
                ('upload', models.FileField(max_length=200, upload_to='marksheet')),
            ],
        ),
    ]
