# Generated by Django 3.0.6 on 2020-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('sheet', models.FileField(upload_to='marksheet')),
                ('subcode', models.ManyToManyField(default=2, related_name='subjects', to='AddSubject.Subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Chem',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Math',
        ),
        migrations.DeleteModel(
            name='Physics',
        ),
    ]
