# Generated by Django 3.0 on 2020-04-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0002_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='sub_code',
        ),
        migrations.AlterField(
            model_name='mark',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mark',
            name='upload',
            field=models.FileField(upload_to='marksheet'),
        ),
    ]
