# Generated by Django 2.2.12 on 2020-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0003_auto_20200426_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studname', models.CharField(max_length=100)),
                ('studroll', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('branchname', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='roll',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
