# Generated by Django 2.2.12 on 2020-05-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0004_auto_20200506_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='roll',
        ),
    ]
