# Generated by Django 3.0.6 on 2020-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSubject', '0004_auto_20200518_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='subjectcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
